const express = require('express');
const router = express.Router();
const userController = require('../app/controllers/UserController');
const AuthMiddleware = require('../app/middlewares/AuthMiddleware');
router.get('/sign-in', userController.signIn);
router.post('/sign-in', userController.confirmSignIn);
router.get('/sign-up', userController.signUp);
router.post('/sign-up',userController.register);
router.get('/profile',userController.profile);
router.get('/changepass',userController.changePasswords);
router.post('/changepass',userController.changePass);
router.post('/logout',userController.logout);
module.exports = router;
